[package]
name = "seaport-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }
# tokio = { version = "1", features = ["full"] }
# eyre = "0.6"
